name: Archive Raw

on:
  workflow_run:
    workflows: [Fetch All]
    types:
      - completed
  workflow_dispatch:

jobs:
  archive-raw:
    strategy:
      fail-fast: false
      matrix:
        target:
          - "alma-errata"
          - "alma-osv"
          - "alma-oval"
          - "alpine-osv"
          - "alpine-secdb"
          - "alt-oval"
          - "amazon"
          - "android-osv"
          - "anolis-oval"
          - "arch"
          - "attack"
          - "azure-oval"
          - "bitnami-osv"
          - "capec"
          # - "cargo-db"
          - "cargo-ghsa"
          - "cargo-osv"
          - "chainguard-osv"
          - "chainguard-secdb"
          - "cisa-kev"
          - "cisco-csaf"
          - "cisco-cvrf"
          - "cisco-json"
          # - "composer-db"
          - "composer-ghsa"
          - "composer-glsa"
          - "composer-osv"
          - "conan-glsa"
          - "cwe"
          - "debian-osv"
          - "debian-oval"
          - "debian-security-tracker-api"
          - "debian-security-tracker-salsa"
          - "echo"
          - "endoflife-date-api"
          - "endoflife-date-products"
          - "erlang-ghsa"
          - "erlang-osv"
          - "exploit-exploitdb"
          - "exploit-github"
          - "exploit-inthewild"
          - "exploit-trickest"
          - "fedora"
          - "fortinet-cvrf"
          - "freebsd"
          - "gentoo"
          - "ghactions-osv"
          - "git-osv"
          # - "golang-db"
          - "golang-ghsa"
          - "golang-glsa"
          - "golang-osv"
          # - "golang-vulndb"
          - "haskell-osv"
          - "jvn-feed-detail"
          - "jvn-feed-product"
          - "jvn-feed-rss"
          - "k8s-json"
          - "k8s-osv"
          - "linux-osv"
          - "mageia-osv"
          - "maven-ghsa"
          - "maven-glsa"
          - "maven-osv"
          - "minimos-secdb"
          # - "mitre-cvrf"
          # - "mitre-v4"
          - "mitre-v5"
          - "msf"
          - "netbsd"
          # - "npm-db"
          - "npm-ghsa"
          - "npm-glsa"
          - "npm-osv"
          - "nuclei-repository"
          - "nuget-ghsa"
          - "nuget-glsa"
          - "nuget-osv"
          - "nvd-api-cpe"
          - "nvd-api-cpematch"
          - "nvd-api-cve"
          - "nvd-feed-cpe-v1"
          - "nvd-feed-cpematch-v1"
          - "nvd-feed-cve-v1"
          - "nvd-feed-cpe-v2"
          - "nvd-feed-cpematch-v2"
          - "nvd-feed-cve-v2"
          - "openeuler-csaf"
          - "openeuler-cvrf"
          - "oracle"
          - "oss-fuzz-osv"
          - "paloalto-csaf"
          - "paloalto-json"
          - "paloalto-list"
          # - "perl-db"
          - "photon-cve"
          - "photon-oval"
          # - "pip-db"
          - "pip-ghsa"
          - "pip-glsa"
          - "pip-osv"
          - "pub-ghsa"
          - "pub-osv"
          - "r-osv"
          - "redhat-csaf"
          - "redhat-cve"
          # - "redhat-cvrf"
          - "redhat-osv"
          # - "redhat-ovalv1"
          - "redhat-ovalv2"
          - "redhat-repository-to-cpe"
          - "redhat-vex"
          - "rocky-errata"
          - "rocky-osv"
          # - "rubygems-db"
          - "rubygems-ghsa"
          - "rubygems-glsa"
          - "rubygems-osv"
          - "snort"
          - "suse-csaf"
          - "suse-csaf-vex"
          - "suse-cvrf"
          - "suse-cvrf-cve"
          - "suse-osv"
          - "suse-oval"
          - "swift-ghsa"
          - "swift-osv"
          - "ubuntu-cve"
          - "ubuntu-cve-tracker"
          - "ubuntu-notice"
          - "ubuntu-osv"
          - "ubuntu-oval"
          - "ubuntu-usndb"
          - "ubuntu-vex"
          - "vulncheck-kev"
          - "windows-advisory"
          # - "windows-bulletin"
          - "windows-csaf"
          - "windows-cvrf"
          - "windows-deployment"
          - "windows-msuc"
          - "windows-product"
          - "windows-vulnerability"
          - "windows-wsusscn2"
          - "wolfi-osv"
          - "wolfi-secdb"
          - "wrlinux"
    uses: ./.github/workflows/archive.yml
    with:
      tag: vuls-data-raw-${{ matrix.target }}
      threshold-mb: 1024

  check-archive-epss:
    name: Check if today is April 1st
    runs-on: ubuntu-latest
    outputs:
      do_archive: ${{ steps.archive_check.outputs.do_archive }}
    steps:
      - name: Decide whether to archive
        id: archive_check
        run: |
          if [ "$(date +'%m-%d')" == "04-01" ]; then
            echo "do_archive=true" >> $GITHUB_OUTPUT
          fi

  archive-epss:
    if: ${{ ( success() || failure() ) && needs.check-archive-epss.outputs.do_archive == 'true' }}
    needs: [check-archive-epss]
    uses: ./.github/workflows/archive-epss.yml
