name: Cleanup vulsio/vuls-data-db

on:
  workflow_run:
    workflows: [Harvest All]
    types:
      - completed

jobs:
  cleanup:
    name: Cleanup untagged images in vulsio/vuls-data-db
    uses: ./.github/workflows/cleanup.yml
    with:
      package: vuls-data-db

  cleanup-archive:
    name: Cleanup untagged images in vulsio/vuls-data-db-archive
    uses: ./.github/workflows/cleanup.yml
    with:
      package: vuls-data-db-archive
