name: Cleanup

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      package:
        required: true
        default: "vuls-data-db"
        type: choice
        options:
          - vuls-data-db
          - vuls-data-db-archive
          - vuls-data-db-backup

jobs:
  cleanup:
    name: Cleanup untagged images in ${{ inputs.package }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version: "stable"

      - name: Install vuls-data-update
        run: go install github.com/MaineK00n/vuls-data-update/cmd/vuls-data-update@main

      - name: Cleanup untagged images
        run: vuls-data-update dotgit registry ls --repositories "ghcr.io/vulsio/${{ inputs.package }}" --token ${{  secrets.GITHUB_TOKEN }} | jq -r '.[] | select(.name == "") | .digest' | xargs -I {} vuls-data-update dotgit registry delete --token ${{ secrets.GITHUB_TOKEN }} ghcr.io/vulsio/${{ inputs.package }}@{}
