name: Cleanup
on:
  workflow_run:
    workflows: [Push, Fetch, Extract, Extract(Nightly)]
    types:
      - completed
  workflow_dispatch:

jobs:
  cleanup:
    name: Cleanup untagged images
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup untagged images
        run: |
          gh api --paginate /orgs/vulsio/packages/container/vuls-data-db/versions --jq '.[] | select(.metadata.container.tags | length == 0) | .id' | xargs -I {} gh api --method DELETE /orgs/vulsio/packages/container/vuls-data-db/versions/{}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
