name: Extract EOL

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: choice
        options:
          - main
          - nightly

jobs:
  extract:
    name: Extract vuls-data-extracted-eol@${{ inputs.branch }}
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 32768
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v5
        with:
          repository: MaineK00n/vuls-data-update
          ref: ${{ inputs.branch }}

      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Install vuls-data-update
        run: go install ./cmd/vuls-data-update

      - name: Pull ghcr.io/${{ github.repository }}:vuls-data-extracted-eol
        run: vuls-data-update dotgit pull --dir . --checkout ${{ inputs.branch }} ghcr.io/${{ github.repository }}:vuls-data-extracted-eol

      - name: Extract
        run: vuls-data-update extract eol --dir ghcr.io/${{ github.repository }}/vuls-data-extracted-eol

      - name: Set Git config
        run: |
          if git -C ghcr.io/${{ github.repository }}/vuls-data-extracted-eol remote | grep -q "^origin$"; then
            git -C ghcr.io/${{ github.repository }}/vuls-data-extracted-eol remote set-url origin ghcr.io/${{ github.repository }}:vuls-data-extracted-eol
          else
            git -C ghcr.io/${{ github.repository }}/vuls-data-extracted-eol remote add origin ghcr.io/${{ github.repository }}:vuls-data-extracted-eol
          fi
          git -C ghcr.io/${{ github.repository }}/vuls-data-extracted-eol config user.email "action@github.com"
          git -C ghcr.io/${{ github.repository }}/vuls-data-extracted-eol config user.name "GitHub Action"

      - name: Commit
        run: |
          if [[ -n $(git -C ghcr.io/${{ github.repository }}/vuls-data-extracted-eol status --porcelain) ]]; then
            git -C ghcr.io/${{ github.repository }}/vuls-data-extracted-eol add .
            git -C ghcr.io/${{ github.repository }}/vuls-data-extracted-eol commit -m "update" -m "GitHub Actions: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs/${{ job.check_run_id }}"
          fi

      - name: Create dotgit tarball
        run: vuls-data-update dotgit compress ghcr.io/${{ github.repository }}/vuls-data-extracted-eol

      - name: Push ghcr.io/${{ github.repository }}:vuls-data-extracted-eol
        run: vuls-data-update dotgit registry push --force --token ${{ secrets.GITHUB_TOKEN }} ghcr.io/${{ github.repository }}:vuls-data-extracted-eol vuls-data-extracted-eol.tar.zst
