name: Extract RedHat RHEL Only (OVALv1)

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: choice
        options:
          - main
          - nightly

jobs:
  extract:
    name: Extract vuls-data-extracted-redhat-ovalv1-rhel@${{ inputs.branch }}
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 32768
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"

      - name: Install Oras
        run: |
          # https://oras.land/docs/installation/#linux
          VERSION="1.2.2"
          curl -LO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_linux_amd64.tar.gz"
          mkdir -p oras-install/
          tar -zxf oras_${VERSION}_*.tar.gz -C oras-install/
          sudo mv oras-install/oras /usr/local/bin/
          rm -rf oras_${VERSION}_*.tar.gz oras-install/

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          repository: MaineK00n/vuls-data-update
          ref: ${{ inputs.branch }}

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Install vuls-data-update
        run: go install ./cmd/vuls-data-update

      - name: Pull ghcr.io/${{ github.repository }}:vuls-data-raw-redhat-ovalv1
        run: |
          oras pull ghcr.io/${{ github.repository }}:vuls-data-raw-redhat-ovalv1
          tar -xf vuls-data-raw-redhat-ovalv1.tar.zst
          rm vuls-data-raw-redhat-ovalv1.tar.zst
          git -C vuls-data-raw-redhat-ovalv1 restore .

      - name: Pull ghcr.io/${{ github.repository }}:vuls-data-raw-redhat-repository-to-cpe
        run: |
          oras pull ghcr.io/${{ github.repository }}:vuls-data-raw-redhat-repository-to-cpe
          tar -xf vuls-data-raw-redhat-repository-to-cpe.tar.zst
          rm vuls-data-raw-redhat-repository-to-cpe.tar.zst
          git -C vuls-data-raw-redhat-repository-to-cpe restore .

      - name: Replace empty repository-to-cpe data
        run: |
          echo "{}" > vuls-data-raw-redhat-repository-to-cpe/repository-to-cpe.json

      - name: Pull ghcr.io/${{ github.repository }}:vuls-data-extracted-redhat-ovalv1-rhel
        run: |
          oras pull ghcr.io/${{ github.repository }}:vuls-data-extracted-redhat-ovalv1-rhel
          tar -xf vuls-data-extracted-redhat-ovalv1-rhel.tar.zst
          rm vuls-data-extracted-redhat-ovalv1-rhel.tar.zst
          git -C vuls-data-extracted-redhat-ovalv1-rhel switch ${{ inputs.branch }}

      - name: Extract
        run: vuls-data-update extract redhat-ovalv1 --dir vuls-data-extracted-redhat-ovalv1-rhel vuls-data-raw-redhat-ovalv1 vuls-data-raw-redhat-repository-to-cpe

      - name: Set Git config
        run: |
          git -C vuls-data-extracted-redhat-ovalv1-rhel remote set-url origin ghcr.io/${{ github.repository }}:vuls-data-extracted-redhat-ovalv1-rhel
          git -C vuls-data-extracted-redhat-ovalv1-rhel config user.email "action@github.com"
          git -C vuls-data-extracted-redhat-ovalv1-rhel config user.name "GitHub Action"

      - name: Commit
        run: |
          if [[ -n $(git -C vuls-data-extracted-redhat-ovalv1-rhel status --porcelain) ]]; then
            git -C vuls-data-extracted-redhat-ovalv1-rhel add .
            git -C vuls-data-extracted-redhat-ovalv1-rhel commit -m "update"
          fi

      - name: Create dotgit tarball
        run: |
          mv vuls-data-extracted-redhat-ovalv1-rhel vuls-data-extracted-redhat-ovalv1-rhel.tmp
          mkdir vuls-data-extracted-redhat-ovalv1-rhel
          mv vuls-data-extracted-redhat-ovalv1-rhel.tmp/.git vuls-data-extracted-redhat-ovalv1-rhel
          tar --remove-files -acf vuls-data-extracted-redhat-ovalv1-rhel.tar.zst vuls-data-extracted-redhat-ovalv1-rhel || [[ $? == 1 ]]

      - name: Login to GitHub Packages Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push ghcr.io/${{ github.repository }}:vuls-data-extracted-redhat-ovalv1-rhel
        run: |
          oras push ghcr.io/${{ github.repository }}:vuls-data-extracted-redhat-ovalv1-rhel vuls-data-extracted-redhat-ovalv1-rhel.tar.zst:application/vnd.vulsio.vuls-data-db.dotgit.layer.v1.tar+zstd
