name: Fetch All

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  fetch-main:
    name: Fetch vuls-data-raw-${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - "alma-errata"
          - "alma-osv"
          - "alma-oval"
          - "alpine-secdb"
          - "alpine-osv"
          - "amazon"
          - "android-osv"
          - "arch"
          - "attack"
          - "bitnami-osv"
          - "capec"
          - "cargo-ghsa"
          - "cargo-osv"
          # - "cargo-db"
          - "chainguard-osv"
          - "composer-ghsa"
          - "composer-glsa"
          - "composer-osv"
          # - "composer-db"
          - "conan-glsa"
          - "cwe"
          - "debian-osv"
          - "debian-oval"
          - "debian-security-tracker-api"
          - "debian-security-tracker-salsa"
          - "erlang-ghsa"
          - "erlang-osv"
          - "exploit-exploitdb"
          - "exploit-github"
          - "exploit-inthewild"
          - "exploit-trickest"
          - "freebsd"
          - "gentoo"
          - "ghactions-osv"
          - "git-osv"
          - "golang-ghsa"
          - "golang-glsa"
          - "golang-osv"
          # - "golang-db"
          # - "golang-vulndb"
          - "haskell-osv"
          - "jvn-feed-detail"
          - "jvn-feed-product"
          - "jvn-feed-rss"
          - "kev"
          - "linux-osv"
          - "maven-ghsa"
          - "maven-glsa"
          - "maven-osv"
          # - "mitre-cvrf"
          # - "mitre-v4"
          - "mitre-v5"
          - "msf"
          - "netbsd"
          - "npm-ghsa"
          - "npm-glsa"
          - "npm-osv"
          # - "npm-db"
          - "nuget-ghsa"
          - "nuget-glsa"
          - "nuget-osv"
          - "nvd-feed-cve"
          - "nvd-feed-cpe"
          - "nvd-feed-cpematch"
          - "oracle"
          - "oss-fuzz-osv"
          # - "perl-db"
          - "pip-ghsa"
          - "pip-glsa"
          - "pip-osv"
          # - "pip-db"
          - "pub-ghsa"
          - "pub-osv"
          - "r-osv"
          - "redhat-cve"
          - "redhat-csaf"
          # - "redhat-cvrf"
          - "redhat-repository-to-cpe"
          # - "redhat-ovalv1"
          - "redhat-ovalv2"
          - "redhat-vex"
          - "redhat-osv"
          - "rocky-errata"
          - "rocky-osv"
          - "rubygems-ghsa"
          - "rubygems-glsa"
          - "rubygems-osv"
          # - "rubygems-db"
          - "snort"
          - "suse-oval"
          - "suse-cvrf"
          - "suse-cvrf-cve"
          - "suse-csaf"
          - "suse-csaf-vex"
          - "suse-osv"
          - "swift-ghsa"
          - "swift-osv"
          - "ubuntu-oval"
          - "ubuntu-cve-tracker"
          - "ubuntu-osv"
          # - "windows-bulletin"
          - "windows-cvrf"
          - "windows-csaf"
          - "windows-wsusscn2"
          - "wolfi-osv"
    uses: ./.github/workflows/fetch-main.yml
    with:
      target: ${{ matrix.target }}

  fetch-nvd-api:
    name: Fetch vuls-data-raw-${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - "nvd-api-cve"
          - "nvd-api-cpe"
          - "nvd-api-cpematch"
    uses: ./.github/workflows/fetch-nvd-api.yml
    with:
      target: ${{ matrix.target }}
    secrets:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

  fetch-msuc:
    name: Fetch vuls-data-raw-windows-msuc
    uses: ./.github/workflows/fetch-msuc.yml

  fetch-fedora:
    name: Fetch vuls-data-raw-fedora
    uses: ./.github/workflows/fetch-fedora.yml

  fetch-epss:
    name: Fetch vuls-data-raw-epss
    uses: ./.github/workflows/fetch-epss.yml

  fetch-fortinet-cvrf:
    name: Fetch vuls-data-raw-fortinet-cvrf
    uses: ./.github/workflows/fetch-fortinet-cvrf.yml

  fetch-vulncheck:
    name: Fetch vuls-data-raw-${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - "vulncheck-kev"
    uses: ./.github/workflows/fetch-vulncheck.yml
    with:
      target: ${{ matrix.target }}
    secrets:
      VULNCHECK_API_KEY: ${{ secrets.VULNCHECK_API_KEY }}
