name: Fetch RedHat Package Manifest

on:
  workflow_call:
  workflow_dispatch:

jobs:
  fetch:
    name: Fetch vuls-data-raw-redhat-package-manifest
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 32768
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"

      - name: Install Oras
        run: |
          # https://oras.land/docs/installation/#linux
          VERSION="1.2.2"
          curl -LO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_linux_amd64.tar.gz"
          mkdir -p oras-install/
          tar -zxf oras_${VERSION}_*.tar.gz -C oras-install/
          sudo mv oras-install/oras /usr/local/bin/
          rm -rf oras_${VERSION}_*.tar.gz oras-install/

      - name: Check out code into the Go module directory
        uses: actions/checkout@v5
        with:
          repository: MaineK00n/vuls-data-update
          ref: main

      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Install vuls-data-update
        run: go install ./cmd/vuls-data-update

      - name: Pull ghcr.io/${{ github.repository }}:vuls-data-raw-redhat-package-manifest
        run: |
          oras pull ghcr.io/${{ github.repository }}:vuls-data-raw-redhat-package-manifest
          tar -xf vuls-data-raw-redhat-package-manifest.tar.zst
          rm vuls-data-raw-redhat-package-manifest.tar.zst

      - name: Fetch all
        run: vuls-data-update fetch redhat-package-manifest --dir vuls-data-raw-redhat-package-manifest 8 9 10

      - name: Set Git config
        run: |
          if git -C vuls-data-raw-redhat-package-manifest remote | grep -q "^origin$"; then
            git -C vuls-data-raw-redhat-package-manifest remote set-url origin ghcr.io/${{ github.repository }}:vuls-data-raw-redhat-package-manifest
          else
            git -C vuls-data-raw-redhat-package-manifest remote add origin ghcr.io/${{ github.repository }}:vuls-data-raw-redhat-package-manifest
          fi
          git -C vuls-data-raw-redhat-package-manifest config user.email "action@github.com"
          git -C vuls-data-raw-redhat-package-manifest config user.name "GitHub Action"

      - name: Commit
        run: |
          if [[ -n $(git -C vuls-data-raw-redhat-package-manifest status --porcelain) ]]; then
            git -C vuls-data-raw-redhat-package-manifest add .
            git -C vuls-data-raw-redhat-package-manifest commit -m "update"
          fi

      - name: Create dotgit tarball
        run: |
          mv vuls-data-raw-redhat-package-manifest vuls-data-raw-redhat-package-manifest.tmp
          mkdir vuls-data-raw-redhat-package-manifest
          mv vuls-data-raw-redhat-package-manifest.tmp/.git vuls-data-raw-redhat-package-manifest
          tar --remove-files -acf vuls-data-raw-redhat-package-manifest.tar.zst vuls-data-raw-redhat-package-manifest || [[ $? == 1 ]]

      - name: Login to GitHub Packages Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push ghcr.io/${{ github.repository }}:vuls-data-raw-redhat-package-manifest
        run: |
          oras push ghcr.io/${{ github.repository }}:vuls-data-raw-redhat-package-manifest vuls-data-raw-redhat-package-manifest.tar.zst:application/vnd.vulsio.vuls-data-db.dotgit.layer.v1.tar+zstd
