name: Harvest Post Raw EPSS

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      pack-threads:
        required: true
        default: 2
        type: number
      pack-windowMemory:
        required: true
        default: 4g
        type: string

jobs:
  gc:
    name: Git GC ${{ inputs.tag }}
    uses: ./.github/workflows/gc.yml
    with:
      repository: ${{ github.repository }}
      tag: ${{ inputs.tag }}
      pack-threads: ${{ inputs.pack-threads }}
      pack-windowMemory: ${{ inputs.pack-windowMemory }}

  check:
    name: Check if today is April 1st
    needs: [gc]
    runs-on: ubuntu-latest
    outputs:
      do_archive: ${{ steps.archive_check.outputs.do_archive }}
    steps:
      - name: Decide whether to archive
        id: archive_check
        run: |
          if [ "$(date +'%m-%d')" == "04-01" ]; then
            echo "do_archive=true" >> $GITHUB_OUTPUT
          fi

  archive:
    name: Archive ${{ inputs.tag }}
    needs: [check]
    if: ${{ needs.check.outputs.do_archive == 'true' }}
    uses: ./.github/workflows/archive-epss.yml

  gc-archive:
    name: GC vulsio/vuls-data-db-archive:${{ matrix.tag }}
    needs: [archive]
    if: ${{ needs.archive.outputs.tags != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        tag: ${{ fromJson(needs.archive.outputs.tags) }}
    uses: ./.github/workflows/gc.yml
    with:
      repository: vulsio/vuls-data-db-archive
      tag: ${{ matrix.tag }}
      pack-threads: ${{ inputs.pack-threads }}
      pack-windowMemory: ${{ inputs.pack-windowMemory }}
