name: Harvest Post Extracted

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      pack-threads:
        required: true
        default: 2
        type: number
      pack-windowMemory:
        required: true
        default: 4g
        type: string

jobs:
  gc:
    name: Git GC ${{ inputs.tag }}
    uses: ./.github/workflows/gc.yml
    with:
      repository: ${{ github.repository }}
      tag: ${{ inputs.tag }}
      pack-threads: ${{ inputs.pack-threads }}
      pack-windowMemory: ${{ inputs.pack-windowMemory }}

  check:
    name: Check ${{ inputs.tag }} Layer Size
    needs: [gc]
    uses: ./.github/workflows/check-layer-size.yml
    with:
      repository: ${{ github.repository }}
      tag: ${{ inputs.tag }}
      media-type: application/vnd.vulsio.vuls-data-db.dotgit.layer.v1.tar+zstd
      threshold-mb: 1024

  truncate:
    name: Truncate ${{ inputs.tag }}
    needs: [check]
    if: ${{ needs.check.outputs.exceeded == 'true' }}
    uses: ./.github/workflows/truncate.yml
    with:
      tag: ${{ inputs.tag }}
      log-ratio: 0.8
