name: Organize Tags in vulsio/vuls-data-db-backup

on:
  workflow_run:
    workflows: [Backup Daily, Backup Weekly, Backup Monthly]
    types:
      - completed
  workflow_dispatch:

jobs:
  cleanup:
    name: Organize Tags in vulsio/vuls-data-db-backup
    uses: ./.github/workflows/organize-tags.yml
    with:
      package: vuls-data-db-backup
